language: php

php:
    - 5.5
    
before_script:


script:
    - phpunit --verbose ./test/test.php
    
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: s3
  access_key_id: AKIAIHVMWLHEDUZ6NWQA
  secret_access_key: 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
  bucket: francis.parrilla
  local-dir: s3
  region: us-east-1
