language: php

php:
    - 5.5
    
before_script:


script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml
    - phpunit --verbose ./test/test.php
    
after_success:
  - bash <(curl -s https://codecov.io/bash)
